name: Rust

on: [push]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable rust release
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.39.0
          override: true
          components: rustfmt, clippy

      - name: Check source formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
